Manually fix errors that IWYU treat as fatal
1) vehicle.h requires knowing the size of class npc, but does not include npc.h.
This trips IWYU in the following way:

In file included from /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/vehicle_display.cpp:1:
In file included from /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/vehicle.h:22:
In file included from /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/active_item_cache.h:10:
In file included from /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/coordinates.h:18:
In file included from /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/cuboid_rectangle.h:5:
In file included from /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/cata_utility.h:12:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/memory:78:
Error: /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/unique_ptr.h:91:16: error: invalid application of 'sizeof' to an incomplete type 'npc'
   91 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/unique_ptr.h:398:4: note: in instantiation of member function 'std::default_delete<npc>::operator()' requested here
  398 |           get_deleter()(std::move(__ptr));
      |           ^
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/vehicle.h:246:9: note: in instantiation of member function 'std::unique_ptr<npc>::~unique_ptr' requested here
  246 |         turret_cpu() = default;
      |         ^
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/dialogue_helpers.h:24:7: note: forward declaration of 'npc'
   24 | class npc;
      |       ^

The fix is to add #include "npc.h".

2) That has some knock-on effects.
(specifically it starts complaining that [files included in] npc.h do not have neccessary
forward includes)
So fix those too (in, hopefully, an obvious fashion)

3) event_statistics.h refers to private `class impl`, but that
reference is ambiguous (because we have many `class impl`s!)
so fully qualify that one to make IWYU less confused